# ???????????????
server:
  port: 8080
  servlet:
    context-path: /bdai


# ????????????????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nybike
    username: root
    password: 123456


# ??MyBatis ? SQL????????????????mapper???? .xml ?????
mybatis:
  mapper-locations: classpath:mapper/*.xml
